/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package snakeandladder;

/**
 *
 * @author Prudhvi
 */
public class NewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public NewJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        PlayerNoComboBox = new javax.swing.JComboBox();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel3.setText("Player 2 Name:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 358, -1, -1));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel1.setText("Select Number of Players");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 152, 297, 35));

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel4.setText("Player 3 Name:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 436, -1, -1));

        jTextField1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 275, 158, -1));

        PlayerNoComboBox.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        PlayerNoComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "1 player", "2 Players", "3 Players" }));
        PlayerNoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayerNoComboBoxActionPerformed(evt);
            }
        });
        add(PlayerNoComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 152, 116, 35));

        jTextField2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 355, 158, -1));

        jTextField3.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 433, 158, -1));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel2.setText("Player 1 Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 275, -1, -1));

        jLabel5.setBackground(new java.awt.Color(255, 0, 0));
        jLabel5.setOpaque(true);
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 275, 73, 27));

        jLabel6.setBackground(new java.awt.Color(0, 51, 204));
        jLabel6.setOpaque(true);
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 355, 73, 27));

        jLabel7.setBackground(new java.awt.Color(51, 255, 0));
        jLabel7.setOpaque(true);
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 433, 73, 27));
    }// </editor-fold>//GEN-END:initComponents

    private void PlayerNoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayerNoComboBoxActionPerformed

        int numberofplayers=PlayerNoComboBox.getSelectedIndex();
        System.out.println("hahaha");
        switch(numberofplayers)
        {
            case 1:
            jLabel2.setVisible(true);
            jLabel3.setVisible(false);
            jLabel4.setVisible(false);
            jTextField1.setVisible(true);
            jTextField2.setVisible(false);
            jTextField3.setVisible(false);
            jLabel5.setVisible(true);
            jLabel6.setVisible(false);
            jLabel7.setVisible(false);
            break;
            case 2:
            jLabel2.setVisible(true);
            jLabel3.setVisible(true);
            jLabel4.setVisible(false);
            jTextField1.setVisible(true);
            jTextField2.setVisible(true);
            jTextField3.setVisible(false);
            jLabel5.setVisible(true);
            jLabel6.setVisible(true);
            jLabel7.setVisible(false);
            break;
            case 3:
            jLabel2.setVisible(true);
            jLabel3.setVisible(true);
            jLabel4.setVisible(true);
            jTextField1.setVisible(true);
            jTextField2.setVisible(true);
            jTextField3.setVisible(true);
            jLabel5.setVisible(true);
            jLabel6.setVisible(true);
            jLabel7.setVisible(true);
            break;
            default:
            jLabel2.setVisible(false);
            jLabel3.setVisible(false);
            jLabel4.setVisible(false);
            jTextField1.setVisible(false);
            jTextField2.setVisible(false);
            jTextField3.setVisible(false);
                jLabel5.setVisible(false);
            jLabel6.setVisible(false);
            jLabel7.setVisible(false);
        }

    }//GEN-LAST:event_PlayerNoComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox PlayerNoComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
